/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
//package reportes;

//import com.mysql.cj.xdevapi.Statement;
import codigos.ClsConexion;
//import com.mysql.cj.Session;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.imageio.ImageIO;
import javax.mail.*;
import javax.mail.Message;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
//import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import static org.castor.core.util.Messages.message;



/**
 *
 * @author Luis
 */
public class VentanaPokedex extends javax.swing.JFrame {
    
    BufferedImage buffer1 = null;
    Image imagen1 = null;
    int contador = 0;
    String neimPokemon = "";
    
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;
    
    
    @Override
    public void paint(Graphics g){
        super.paintComponents(g);
        
        Graphics2D  g2 = (Graphics2D) imagenPokemon.getGraphics();
        
        g2.drawImage(buffer1,0,0,imagenPokemon.getWidth(),
                imagenPokemon.getHeight(),null);
        
        
    }
    
    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        initComponents();
        
        try {
            //imagen1 = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
            imagen1 = ImageIO.read(new File("C:\\Users\\Usuario 2021\\Downloads\\datos\\imagenes\\black-white.png"));
            //le di en importar javax image io.
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }
        buffer1 = (BufferedImage) imagenPokemon.createImage(
        imagenPokemon.getWidth(),
        imagenPokemon.getHeight()
        );
        
        Graphics2D g2 = buffer1.createGraphics();
        
        dibujaElPokemonQueEstaEnLaPosicion(30);
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String JDBC_URL="jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=UTC"; 
            conexion = DriverManager.getConnection(JDBC_URL,"root","1l2u3i4s");
            estado = conexion.createStatement();
        
        
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace(System.out);
        } catch (SQLException ex) {
             ex.printStackTrace(System.out);
        }
        
    }
    
    //no tocar esta wea xd
    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion){
        
        int fila = posicion / 31;
        int columna = posicion % 31;
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.black);
        g2.fillRect(0, 0, //pinta el fondo del jpanel negro
                imagenPokemon.getWidth(),
                imagenPokemon.getHeight()); 
        g2.drawImage(imagen1,
                0,  //posicion X inicial dentro del jpanel 
                0,  // posicion Y inicial dentro del jpanel
                imagenPokemon.getWidth(), //ancho del jpanel
                imagenPokemon.getHeight(), //alto del jpanel
                columna*96, //posicion inicial X dentro de la imagen de todos los pokemon
                fila*96, //posicion inicial Y dentro de la imagen de todos los pokemon
                columna*96 + 96, //posicion final X
                fila*96 + 96, //posicion final Y
                null  //si no lo pones no va
                );
        repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPokemon = new javax.swing.JPanel();
        izq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        der = new javax.swing.JButton();
        nombrePokemon = new javax.swing.JLabel();
        resultados_query = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblResul = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblHabitat = new javax.swing.JLabel();
        lblRatioCap = new javax.swing.JLabel();
        lblExpBase = new javax.swing.JLabel();
        txtPuchamon = new javax.swing.JLabel();
        btnBuscarFiltros = new javax.swing.JButton();
        lblBusquedaxFiltro = new javax.swing.JLabel();
        lblBuscarPersona = new javax.swing.JLabel();
        btnVerUsuarios = new javax.swing.JButton();
        lblReporte = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        btnCorreo = new javax.swing.JButton();
        txtCorreo = new javax.swing.JLabel();
        txtCorreoC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        izq.setText("<==Izquierda");
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });

        der.setText("Derecha==>");
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });

        nombrePokemon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombrePokemon.setText("jLabel2");

        resultados_query.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultados_query.setText("jLabel2");

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscar.setText("jTextField1");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar pokemon");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblResul.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblResul.setText("jLabel2");

        lblColor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblColor.setText("jLabel2");

        lblHabitat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHabitat.setText("jLabel2");

        lblRatioCap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRatioCap.setText("jLabel2");

        lblExpBase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExpBase.setText("jLabel2");

        txtPuchamon.setText("Buscar pokemon:");

        btnBuscarFiltros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscarFiltros.setText("Buscar con filtro");
        btnBuscarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFiltrosActionPerformed(evt);
            }
        });

        lblBusquedaxFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBusquedaxFiltro.setText("Busqueda por filtro:");

        lblBuscarPersona.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBuscarPersona.setText("Datos de usuarios:");

        btnVerUsuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerUsuarios.setText("Ver datos de usuarios");
        btnVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuariosActionPerformed(evt);
            }
        });

        lblReporte.setText("Generar reporte:");

        btnReporte.setText("Genera Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnCorreo.setText("Envio de correo");
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });

        txtCorreo.setText("Enviar correo:");

        txtCorreoC.setText("label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBuscar)
                                    .addComponent(txtPuchamon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVerUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblReporte)
                                                .addComponent(der))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCorreo)))
                                        .addGap(23, 23, 23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBuscarPersona)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBusquedaxFiltro)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnBuscarFiltros)
                                            .addGap(81, 81, 81)
                                            .addComponent(btnReporte))))
                                .addGap(0, 30, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultados_query, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(izq, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(nombrePokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblResul, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                            .addComponent(lblHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addComponent(lblRatioCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblExpBase, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtPuchamon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblBusquedaxFiltro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFiltros)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerUsuarios)
                        .addGap(40, 40, 40)
                        .addComponent(lblReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombrePokemon)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCorreo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCorreoC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblExpBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(23, 23, 23)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(izq)
                            .addComponent(der))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblColor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHabitat)
                            .addComponent(lblRatioCap))
                        .addGap(50, 50, 50)))
                .addComponent(resultados_query))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
        
        contador --;
        if(contador <=0){
            contador = 1;
        }
       dibujaElPokemonQueEstaEnLaPosicion(contador);
        
       String cuerito = "Select * from pokemon where id="+(contador+1);
        
        
        try {
            resultadoConsulta = estado.executeQuery(cuerito);
            if (resultadoConsulta.next()){
                nombrePokemon.setText(resultadoConsulta.getString(2));
                resultados_query.setText("Contador: "+contador+" Cuerito: "+cuerito);
            } else {
                nombrePokemon.setText("Este chucho no esta en el pokedex");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            JOptionPane.showMessageDialog(null,"Clavo con sql");
        }
       
    }//GEN-LAST:event_izqActionPerformed

    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed
        
        dibujaElPokemonQueEstaEnLaPosicion(contador);
        
        String cuerito = "Select * from pokemon where id="+(contador+1);
        
        
        try {
            resultadoConsulta = estado.executeQuery(cuerito);
            if (resultadoConsulta.next()){
                nombrePokemon.setText(resultadoConsulta.getString(2));
                lblResul.setText(resultadoConsulta.getNString(5)); //nice, ya se como ir poniendolos xd
                lblColor.setText(resultadoConsulta.getNString(13));
                lblHabitat.setText(resultadoConsulta.getNString(15));
                lblRatioCap.setText(resultadoConsulta.getNString(16));
                lblExpBase.setText(resultadoConsulta.getNString(17));
                resultados_query.setText("Contador: "+contador+" Cuerito: "+cuerito);
            } else {
                nombrePokemon.setText("Este pokemon no esta en la pokedex");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            JOptionPane.showMessageDialog(null,"Ocurrio un problema con sql");
        }
        
        contador++;
        if (contador >=649){
            contador = 649;
        }
        
    }//GEN-LAST:event_derActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        Connection con = null;
        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        neimPokemon = txtBuscar.getText();
        
        dibujaElPokemonQueEstaEnLaPosicion(contador);
        
        String cuerito3d = "Select * from pokemon where name=?";
        
        
        
        
        try {
            
            conn = ClsConexion.getConnection();
            stmt = conn.prepareStatement(cuerito3d);
            stmt.setString(1,txtBuscar.getText());
            
            rs = stmt.executeQuery();
            
            if(rs.next()){
                
                nombrePokemon.setText(rs.getString("name"));
                lblResul.setText(rs.getNString("generation_id"));
                lblColor.setText(rs.getNString("color"));
                lblHabitat.setText(rs.getNString("habitat"));
                lblRatioCap.setText(rs.getNString("capture_rate"));
                lblExpBase.setText(rs.getNString("base_experience"));
                resultados_query.setText("Contador: "+contador+" Cuerito: "+cuerito3d);
                
            }else{
                
                JOptionPane.showMessageDialog(null,"No existe ese pokemon");
            }
//            resultadoConsulta = estado.executeQuery(cuerito3d);
//            
//            if (resultadoConsulta.next()){
//                nombrePokemon.setText(resultadoConsulta.getString("name"));
//                lblResul.setText(resultadoConsulta.getNString("generation_id"));
//                lblColor.setText(resultadoConsulta.getNString("color"));
//                lblHabitat.setText(resultadoConsulta.getNString("habitat"));
//                lblRatioCap.setText(resultadoConsulta.getNString("capture_rate"));
//                lblExpBase.setText(resultadoConsulta.getNString("base_experience"));
//                resultados_query.setText("Contador: "+contador+" Cuerito: "+cuerito3d);
//            } else {
//                nombrePokemon.setText("Este pokemon no esta en la pokedex");
//            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            JOptionPane.showMessageDialog(null,"Clavo con sql.");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFiltrosActionPerformed
        // TODO add your handling code here: funcion del boton buscar por filtros aqui.
        
        VentanaFiltro ventana2 = new VentanaFiltro();
        ventana2.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnBuscarFiltrosActionPerformed

    private void btnVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuariosActionPerformed
        // TODO add your handling code here: boton de abrir ventana para favoritos.
        
        VentanaFavoritos ventanaNueva = new VentanaFavoritos();
        ventanaNueva.setVisible(true);
        
    }//GEN-LAST:event_btnVerUsuariosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
         ///TODO add your handling code here:
        Connection conn = null;
        try {
            
            
            conn = ClsConexion.getConnection();
            
            String path = "C:\\Users\\Usuario 2021\\Downloads\\Primer proyecto final progra 2\\Parte del pdf y correo\\pokedex1\\src\\main\\java\\reportes\\reporteOne.jasper";
            
            JasperReport reporte1 = null;
            
            reporte1 = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte1, null, conn);

            //Creamos la vista del reporte
            JasperViewer view = new JasperViewer(jprint, false);

            //Cierre para el reporte, y no se quede la tarea corriendo.
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            //Lo hacemos visible
            view.setVisible(true);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se ha generado el PDF por un error.");
        } catch (JRException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        // TODO add your handling code here:
        
        String remitente = "correo de la U";
        String contrasena = "La contrasena";
        String destino = "correo al que loquieras enviar";
        
        Properties props = new Properties();
        props.setProperty("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.ssl.trust","*");
        props.setProperty("mail.smtp.port","587");
        props.setProperty("mail.smtp.auth","true");
        props.setProperty("mail.smtp.starttls.enable","true");
        props.setProperty("mail.smtp.user",remitente);
        props.setProperty("mail.smtp.clave",contrasena);
        
        Session session = Session.getDefaultInstance(props);
        MimeMessage mensaje;
        try {
            mensaje = new MimeMessage(session);
            
            mensaje.addRecipient(Message.RecipientType.TO, new InternetAddress(destino));
            mensaje.setSubject("Hola este es tu reporte de mysql");
            BodyPart parteTexto = new MimeBodyPart();
            parteTexto.setContent("<b>Hola buen dia, aca abajo esta tu reporte</b>","text/html");
            
            BodyPart parteArchivo = new MimeBodyPart();
            parteArchivo.setDataHandler(new DataHandler(new FileDataSource("C:\\Users\\Usuario 2021\\Downloads\\Primer proyecto final progra 2\\Parte del pdf y correo\\ReporteDex1.pdf"))); ;
            parteArchivo.setFileName("ReporteDex.pdf");
            
            MimeMultipart todo = new MimeMultipart();
            todo.addBodyPart(parteTexto);
            todo.addBodyPart(parteArchivo);
            
            mensaje.setContent(todo);
            
           Transport transporte = session.getTransport("smtp");
           transporte.connect("smtp.gmail.com",remitente,contrasena);
           transporte.sendMessage(mensaje, mensaje.getAllRecipients());
           transporte.close();
           txtCorreoC.setText("Correo enviado!!");
            
        } catch (MessagingException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No se pudo enviar el correo");
        }
        
        
    }//GEN-LAST:event_btnCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarFiltros;
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVerUsuarios;
    private javax.swing.JButton der;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBuscarPersona;
    private javax.swing.JLabel lblBusquedaxFiltro;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblExpBase;
    private javax.swing.JLabel lblHabitat;
    private javax.swing.JLabel lblRatioCap;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblResul;
    private javax.swing.JLabel nombrePokemon;
    private javax.swing.JLabel resultados_query;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtCorreoC;
    private javax.swing.JLabel txtPuchamon;
    // End of variables declaration//GEN-END:variables
}
